<a href="https://colab.research.google.com/github/yacouba700/Bambara_AI/blob/main/MonAiBambara.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# =========================================================
# INSTALLATION
# =========================================================

!pip uninstall -y torchao
!pip install -q datasets==2.18.0 transformers accelerate peft sentencepiece

# =========================================================
# IMPORTS
# =========================================================

import shutil
import warnings
warnings.filterwarnings("ignore")

import torch
import os

from google.colab import drive, userdata
from huggingface_hub import login

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    pipeline,
    DataCollatorForLanguageModeling
)

from peft import (
    LoraConfig,
    get_peft_model,
    TaskType,
    PeftModel
)

from datasets import load_dataset

# =========================================================
# GOOGLE DRIVE
# =========================================================

drive.mount('/content/drive')

drive_model_path = "/content/drive/MyDrive/bambara-ai"
model_path = "/content/bambara-ai"

# =========================================================
# DATASET LOCAL
# =========================================================

drive_dataset = "/content/drive/MyDrive/bambara/dataset.jsonl"
local_dataset = "/content/dataset.jsonl"

# Vérifie si le fichier existe déjà en local
if not os.path.exists(local_dataset):
    shutil.copy(drive_dataset, local_dataset)
    print("Dataset copié en local")
else:
    print("Le dataset existe déjà en local, copie ignorée")

# =========================================================
# HUGGING FACE
# =========================================================

hf_token = userdata.get('HF_TOKEN')

login(token=hf_token)

print("Connexion Hugging Face réussie")

# =========================================================
# GPU
# =========================================================

print("GPU disponible :", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU :", torch.cuda.get_device_name(0))

# =========================================================
# MODÈLE
# =========================================================

model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

tokenizer = AutoTokenizer.from_pretrained(model_name)

tokenizer.pad_token = tokenizer.eos_token

# =========================================================
# CHARGER MODÈLE BASE
# =========================================================

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

model.config.use_cache = False

# =========================================================
# CHARGER ANCIEN LORA SI EXISTE
# =========================================================

if os.path.exists(drive_model_path):

    print("Chargement ancien LoRA...")

    model = PeftModel.from_pretrained(
        model,
        drive_model_path,
        is_trainable=True
    )

else:

    print("Création nouveau LoRA...")

    config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=8,
        lora_alpha=16,
        lora_dropout=0.05,
        bias="none"
    )

    model = get_peft_model(model, config)

# =========================================================
# IMPORTANT
# =========================================================

model.train()

model.print_trainable_parameters()

# =========================================================
# DATASET
# =========================================================

dataset = load_dataset(
    "json",
    data_files=local_dataset,
    split="train"
)

print(dataset)

# TEST RAPIDE
dataset = dataset.shuffle(seed=42).select(range(5000))

# =========================================================
# TOKENIZATION
# =========================================================

def tokenize(example):

    tokens = tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

    tokens["labels"] = tokens["input_ids"].copy()

    return tokens

tokenized_dataset = dataset.map(
    tokenize,
    remove_columns=dataset.column_names
)

# =========================================================
# DATA COLLATOR
# =========================================================

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

# =========================================================
# TRAINING ARGUMENTS
# =========================================================

training_args = TrainingArguments(
    output_dir=model_path,

    per_device_train_batch_size=4,

    gradient_accumulation_steps=1,

    num_train_epochs=2,

    learning_rate=2e-4,

    logging_steps=20,

    save_strategy="no",

    fp16=True,

    report_to="none"
)

# =========================================================
# TRAINER
# =========================================================

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=data_collator
)

# =========================================================
# TRAIN
# =========================================================

trainer.train()

# =========================================================
# SAVE LOCAL
# =========================================================

trainer.save_model(model_path)

tokenizer.save_pretrained(model_path)

# =========================================================
# SAVE DRIVE
# =========================================================

shutil.copytree(
    model_path,
    drive_model_path,
    dirs_exist_ok=True
)

print("Modèle sauvegardé")

# =========================================================
# TEST IA
# =========================================================

chat = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer
)

prompt = """
### Instruction:
Traduire en bambara

### Input:
Je transmets mes savoirs à mes enfants.

### Response:
"""

result = chat(
    prompt,

    max_length=40,

    do_sample=True,

    temperature=0.7,

    top_p=0.9,

    repetition_penalty=1.3,

    eos_token_id=tokenizer.eos_token_id,

    pad_token_id=tokenizer.eos_token_id,

    return_full_text=False
)
print(result[0]["generated_text"])

Found existing installation: torchao 0.10.0
Uninstalling torchao-0.10.0:
  Successfully uninstalled torchao-0.10.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.5/510.5 kB 11.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.9/170.9 kB 12.2 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.2.0 which is incompatible.
Mounted at /content/drive
Dataset copié en local
Connexion Hugging Face réussie
GPU disponible : True
GPU : Tesla T4

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.29k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/551 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/2.20G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Chargement ancien LoRA...
trainable params: 1,126,400 || all params: 1,101,174,784 || trainable%: 0.1023

Generating train split: 0 examples [00:00, ? examples/s]

Dataset({
    features: ['text'],
    num_rows: 37643
})

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Passing `generation_config` together with generation-related arguments=({'do_sample', 'pad_token_id', 'top_p', 'temperature', 'repetition_penalty', 'eos_token_id', 'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=40) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Modèle sauvegardé
N ye n denw ma, a ka sonkunbali ye. "Ne kana ne yere senu na". Nye ni an senjigin de.!nk

In [ ]:
## -- PROJET VOCAL --##

# =========================
# 1. INSTALLATION
# =========================
!pip install -q transformers accelerate torchaudio

# =========================
# 2. IMPORTS
# =========================
from transformers import AutoProcessor, AutoModelForCTC
import torch
import torchaudio
from google.colab import files

# =========================
# 3. CHARGER MMS MODEL
# =========================
model_id = "facebook/mms-1b-all"

processor = AutoProcessor.from_pretrained(model_id)
model = AutoModelForCTC.from_pretrained(model_id)

# =========================
# 4. ACTIVER LANGUE BAMBARA
# =========================
processor.tokenizer.set_target_lang("bam")

# =========================
# 5. UPLOAD AUDIO
# =========================
print("👉 Upload ton fichier audio WAV")
uploaded = files.upload()

audio_path = list(uploaded.keys())[0]

# =========================
# 6. LECTURE AUDIO
# =========================
speech, sr = torchaudio.load(audio_path)

# Resample si nécessaire (MMS = 16kHz)
if sr != 16000:
    resampler = torchaudio.transforms.Resample(sr, 16000)
    speech = resampler(speech)

# =========================
# 7. TRANSCRIPTION
# =========================
inputs = processor(
    speech.squeeze().numpy(),
    sampling_rate=16000,
    return_tensors="pt"
)

with torch.no_grad():
    logits = model(**inputs).logits

pred_ids = torch.argmax(logits, dim=-1)
text = processor.decode(pred_ids[0])

# =========================
# 8. RESULTAT
# =========================
print("\n=======================")
print("🗣️ Transcription Bambara :")
print("=======================")
print(text)

Loading weights:   0%|          | 0/1096 [00:00<?, ?it/s]

👉 Upload ton fichier audio WAV

KeyboardInterrupt:

In [ ]:
from google.colab import drive
import os

# Unmount if already mounted, and remove the directory if it exists and is not empty.
# This handles cases where force_remount=True might not be sufficient if the directory was pre-populated.
if os.path.exists('/content/drive') and os.path.isdir('/content/drive') and os.listdir('/content/drive'):
    # Attempt to unmount first if it's a mounted filesystem
    try:
        !fusermount -uz /content/drive
    except:
        pass # Ignore errors if it wasn't mounted or unmounting failed
    !rm -rf /content/drive

drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [3]:
import json

path = "/content/dataset.jsonl"

with open(path, "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        print(json.loads(line))

        # stop après 5 lignes (optionnel)
       # if i == 30:
           # break

Streaming output truncated to the last 5000 lines.
{'text': '### Instruction:\nRéponds en bambara\n\n### Input:\npleurez plutôt sur vous-mêmes et sur vos enfants!\n\n### Response:\nAw ka kasi aw yɛrɛ ko la, ani aw denw!'}
{'text': "### Instruction:\nRéponds en bambara\n\n### Input:\nCar voici venir des jours où l'on dira: Heureuses les femmes stériles, les entrailles qui n'ont pas enfanté, et les seins qui n'ont pas nourri!\n\n### Response:\nDon dɔw natɔ filɛ, a na fɔ don minnu na, ko : Muso konanw ani minnu ma den bangin, minnu ma sin di den ma, olu kunna ka di !"}
{'text': '### Instruction:\nTraduis cette phrase en bambara\n\n### Input:\nAlors on se mettra à dire aux montagnes: Tombez sur nous! et aux collines: Couvrez-nous!\n\n### Response:\nO la, a na fɔ kulubaw ye: Aw ka bin an kan; ani kuluninw ye: Aw ka an ɲɛmadogo.'}
{'text': "### Instruction:\nDialogue entre amis en bambara\n\n### Input:\nCar si l'on traite ainsi le bois vert, qu'adviendra-t-il du sec?»\n\n### Response:\nNi nin ye jirikɛnɛ minɛcogo ye, jirijalan na kɛ di? »"}
{'text': '### Instruction:\nRéponds en bambara\n\n### Input:\nOn emmenait encore deux malfaiteurs pour être exécutés avec lui.\n\n### Response:\nMɔgɔ fila wɛrɛ minɛna ka fara Yezu kan, u fagali kama. Olu tun ye kojugukɛlaw ye.'}
{'text': '### Instruction:\nRéponds en bambara\n\n### Input:\nLe crucifiement\n\n### Response:\nYezu gengenni kuruwajiri kan'}
{'text': "### Instruction:\nTraduis ce récit en bambara\n\n### Input:\nLorsqu'ils furent arrivés au lieu appelé Crâne, ils l'y crucifièrent ainsi que les malfaiteurs, l'un à droite et l'autre à gauche.\n\n### Response:\nU selen yɔrɔ la min bɛ wele Kunkolokolo wali Kaliwɛri, u ye Yezu gengen kuruwa kan yen. Ani o kojugukɛla fila: kelen a kinin fɛ, kelen a numa fɛ."}
{'text': "### Instruction:\nTraduis cette phrase en bambara\n\n### Input:\nEt Jésus disait: «Père, pardonne-leur: ils ne savent ce qu'ils font.»\n\n### Response:\nYezu ko: «Baba, yafa u ma, ka a masɔrɔ u bɛ ka min kɛ u tɛ o dɔn. »"}
{'text': '### Instruction:\nRéponds en bambara\n\n### Input:\nPuis, se partageant ses vêtements, ils tirèrent au sort.\n\n### Response:\nU ye kala da a ka finiw kan ka olu tila u ni ɲɔgɔn cɛ.'}
{'text': '### Instruction:\nTraduis ce récit en bambara\n\n### Input:\nJésus en croix raillé et outragé\n\n### Response:\nYezu nenini'}
{'text': '### Instruction:\nTraduis cette phrase en bambara\n\n### Input:\nLe peuple se tenait là, à regarder.\n\n### Response:\nJama tun bɛ yen ka kow filɛ;'}
{'text': "### Instruction:\nTexte religieux en bambara\n\n### Input:\nLes chefs, eux, se moquaient: «Il en a sauvé d'autres, disaient-ils; qu'il se sauve lui-même, s'il est le Christ de Dieu, l'Élu!»\n\n### Response:\nɲɛmɔgɔw tun bɛ Yezu ɲagarikɔrɔbɔ ko: «A ye dɔw kisi. A ka a yɛrɛ kisi sa, ni a ye Ala ka Krista ye, ɲɛnatɔmɔnen ! »"}
{'text': '### Instruction:\nTraduis ce récit en bambara\n\n### Input:\nils disaient: «Si tu es le roi des Juifs, sauve-toi toi-même!»\n\n### Response:\nu tun bɛ a fɔ : « Ni i ye Zifuw ka masakɛ ye, i yɛrɛ kisi ! »'}
{'text': '### Instruction:\nNarration en bambara\n\n### Input:\nIl y avait aussi une inscription au-dessus de lui: «Celui-ci est le roi des Juifs.»\n\n### Response:\nA tun sɛbɛnna ka bila a kunyanfan fɛ, ko : « Nin ye Zifuw ka masakɛ ye.»'}
{'text': '### Instruction:\nRéponds en bambara\n\n### Input:\nLe «bon larron»\n\n### Response:\nBinkannikɛla sɔn yɛlɛmali'}
{'text': "### Instruction:\nDialogue entre amis en bambara\n\n### Input:\nL'un des malfaiteurs suspendus à la croix l'injuriait: «N'es-tu pas le Christ?\n\n### Response:\nKojugukɛla minnu tun dulonnen bɛ kuruwa la, olu dɔ la kelen tun bɛ Yezu dɔgɔya ka a fɔ : « E tɛ Krista ye wa ?"}
{'text': '### Instruction:\nRéponds en bambara\n\n### Input:\nSauve-toi toi-même, et nous aussi.»\n\n### Response:\nI yɛrɛ kisi ka an bɔ i nu ma. »'}
{'text': "### Instruction:\nTraduis ce passage religieux en bambara\n\n### Input:\nMais l'autre, le reprenant, déclara: «Tu n'as même pas crainte de Dieu, alors que tu subis la même peine!\n\n### Response:\nNka a tɔɲɔgɔn ye a kɔrɔfɔ, ko : « E tɛ siran Ala ɲɛ wa ? E min fana bɛ o ɲɔgɔn ɲɛgan bolo!"}
{'text': "### Instruction:\nTraduis cette phrase en bambara\n\n### Input:\nPour nous, c'est justice, nous payons nos actes; mais lui n'a rien fait de mal.»\n\n### Response:\nKa fara o kan, anw ni an ta ka kan. An ka ɲɛgan ye an ka wale sara ye. Nka ale kɔni ma kojugu si kɛ. »"}
{'text': '### Instruction:\nRéponds en bambara\n\n### Input:\nEt il disait: «Jésus, souviens-toi de moi, lorsque tu viendras avec ton royaume.»\n\n### Response:\nA ko tugun: «Yezu, i hakili to ne na, ni i donna i ka Masaya la. »'}
{'text': "### Instruction:\nRéponds en bambara\n\n### Input:\nEt il lui dit: «En vérité, je te le dis, aujourd'hui tu seras avec moi dans le Paradis.»\n\n### Response:\nYezu ye a jaabi, ko: «Tiyɛn na ne bɛ a jɛya i ma, bi yɛrɛ i na kɛ ne fɛ arijana na.»"}
{'text': '### Instruction:\nTraduis cette phrase en bambara\n\n### Input:\nLa mort de Jésus\n\n### Response:\nYezu saya'}
{'text': "### Instruction:\nRéponds en bambara\n\n### Input:\nC'était déjà environ la sixième heure quand, le soleil s'éclipsant, l'obscurité se fit sur la terre entière, jusqu'à la neuvième heure.\n\n### Response:\nTilesekuncɛ masurunna ni o ye tile waati wɔɔrɔnan ye, dibiba donna jamana mumɛ kɔnɔ fo ka se tile jɛngɛntuma ma, ka a masɔrɔ tile tun donna muntan na."}
{'text': '### Instruction:\nRéponds en bambara\n\n### Input:\net, jetant un grand cri, Jésus dit: «Père, en tes mains je remets mon esprit.»\n\n### Response:\nO tuma na, Yezu ye kulokanba kelen kɛ, ka a fɔ: «Baba, ne bɛ n ni to i bolo. »'}
{'text': '### Instruction:\nConvertis ce texte en bambara naturel\n\n### Input:\nAyant dit cela, il expira.\n\n### Response:\nO fɔlen kɔ a fɛ, a ye ninakili laban kɛ.'}
{'text': '### Instruction:\nTraduire en bambara\n\n### Input:\nAprès la mort de Jésus\n\n### Response:\nYezu saya kɔ'}
{'text': '### Instruction:\nTraduis ce passage religieux en bambara\n\n### Input:\nVoyant ce qui était arrivé, le centenier glorifiait Dieu, en disant: «Sûrement, cet homme était un juste!»\n\n### Response:\nKo min kɛra, Kɛlɛcɛkɛmɛkuntigi ye o ye ka Ala tanu, ko: «Siga tɛ a la, nin cɛ tun ye mɔgɔ tilennen ye. »'}
{'text': "### Instruction:\nTraduire en bambara\n\n### Input:\nEt toutes les foules qui s'étaient rassemblées pour ce spectacle, voyant ce qui était arrivé, s'en retournaient en se frappant la poitrine.\n\n### Response:\nMɔgɔ minnu tun ye u dalajɛ filɛli kama, olu ye o ko kɛlenw ye minkɛ, u kɔsegintɔ tun bɛ u disi gosi-gosi."}
{'text': "### Instruction:\nRéponds en bambara\n\n### Input:\nTous ses amis se tenaient à distance, ainsi que les femmes qui l'accompagnaient depuis la Galilée, et qui regardaient cela.\n\n### Response:\nYezu teriw bɛɛ ani musow minnu tun tugura a la kabini Galile jamana na, ani minnu tun bɛ filɛli la, olu bɛɛ jɔlen tun bɛ fanan fɛ."}
{'text': "### Instruction:\nTraduis cette phrase en bambara\n\n### Input:\nL'ensevelissement\n\n### Response:\nYezu su donni"}
{'text': '### Instruction:\nTraduis ce récit en bambara\n\n### Input:\nEt voici un homme nommé Joseph, membre du Conseil, homme droit et juste.\n\n### Response:\nO tuma na, Kiribulonba mɔgɔw ka jamakulu mɔgɔ dɔ la kelen nana. O tɔgɔ tun ye ko Zozɛfu. Mɔgɔ ɲuman tun don, ani mɔgɔ laadiri.'}
{'text': "### Instruction:\nConvertis ce texte en bambara naturel\n\n### Input:\nCelui-là n'avait pas donné son assentiment au dessein ni à l'acte des autres.\n\n### Response:\nA tun ma sɔn u ka ɲɔgɔnyekan ma, ani ɲɛmɔgɔw ka walew ma."}
{'text': "### Instruction:\nTexte religieux en bambara\n\n### Input:\nIl était d'Arimathie, ville juive, et il attendait le Royaume de Dieu.\n\n### Response:\nA tun bɛ bɔ Arimati, zifu dugu dɔ don. A sigilen tun bɛ ka Ala ka Masaya tile makɔnɔ."}
{'text': '### Instruction:\nRéponds en bambara\n\n### Input:\nIl alla trouver Pilate et réclama le corps de Jésus.\n\n### Response:\nA taara Pilati yɔrɔ ka Yezu su ɲini o fɛ.'}
{'text': "### Instruction:\nRéponds en bambara\n\n### Input:\nIl le descendit, le roula dans un linceul et le mit dans une tombe taillée dans le roc, où personne encore n'avait été placé.\n\n### Response:\nO kɔ a ye su lajigin ka bɔ kuruwa kan, ka su kasanke ani ka o don kaburu dɔ la min tun sennen farakolo la, mɔgɔ si su tun ma da min kɔnɔ fɔlɔ."}
{'text': "### Instruction:\nRéponds en bambara\n\n### Input:\nC'était le jour de la Préparation, et le sabbat commençait à poindre.\n\n### Response:\nO don tun ye juma ye, lafiyɛndon ɲɛbila. Sabat kun tun bɔra ka ban."}
{'text': '### Instruction:\nRéponds en bambara\n\n### Input:\nCependant les femmes qui étaient venues avec lui de Galilée avaient suivi Joseph; elles regardèrent le tombeau et comment son corps avait été mis.\n\n### Response:\nMuso minnu tun tugura Yezu la kabini Galile jamana na, olu ye u bila Zozɛfu kɔ. U ye kaburu kɔnɔ filɛ walasa ka su dacogo dɔn u fɛ.'}
{'text': "### Instruction:\nTraduis cette phrase en bambara\n\n### Input:\nPuis elles s'en retournèrent et préparèrent aromates et parfums.\n\n### Response:\nO kɔ, u ye u kɔsegin ka taa so ka sumadiyalanw labɛn."}
{'text': '### Instruction:\nConvertis ce texte en bambara naturel\n\n### Input:\nEt le sabbat, elles se tinrent en repos, selon le précepte.\n\n### Response:\nSibiridon sariya dantigɛlen, u ye o tiimɛ.'}
{'text': '### Instruction:\nTraduis cette phrase en bambara\n\n### Input:\nChapitre 24\n\n### Response:\n24'}
{'text': '### Instruction:\nConvertis ce texte en bambara naturel\n\n### Input:\nLe tombeau vide.\n\n### Response:\nKaburu lankolon'}
{'text': "### Instruction:\nTraduis cette phrase en bambara\n\n### Input:\nLe premier jour de la semaine, à la pointe de l'aurore, elles allèrent à la tombe, portant les aromates qu'elles avaient préparés.\n\n### Response:\nDɔgɔkun tile fɔlɔ sɔgɔmada joona fɛ, musow taara kaburu la. Sumadiyalanw tun bɛ u bolo, u tun ye minnu labɛn."}
{'text': '### Instruction:\nTraduis cette phrase en bambara\n\n### Input:\nmais, étant entrées, elles ne trouvèrent pas le corps du Seigneur Jésus.\n\n### Response:\nU donna nka u ma Matigi su sɔrɔ yen.'}
{'text': '### Instruction:\nTraduis cette phrase en bambara\n\n### Input:\nEt il advint, comme elles en demeuraient perplexes, que deux hommes se tinrent devant elles, en habit éblouissant.\n\n### Response:\nU hakili tiyɛnna. O tuma na, cɛ fila ye u yɛrɛ jira u la. Olu kannadulɔki tun bɛ yelenkun.'}
{'text': "### Instruction:\nDiscussion en bambara\n\n### Input:\nEt tandis que, saisies d'effroi, elles tenaient leur visage incliné vers le sol, ils leur dirent: «Pourquoi cherchez-vous le Vivant parmi les morts?\n\n### Response:\nU siranbagatɔ ye u ɲɛda suuli. Cɛ fila ninnu ko u ye : « Mun na aw bɛ ɲɛnama ɲini suw cɛ la ?"}
{'text': "### Instruction:\nConvertis ce texte en bambara naturel\n\n### Input:\nIl n'est pas ici; mais il est ressuscité.\n\n### Response:\nA tɛ yan, a kununna."}
{'text': "### Instruction:\nConte traditionnel en bambara\n\n### Input:\nRappelez-vous comment il vous a parlé, quand il était encore en Galilée: Il faut, disait-il, que le Fils de l'homme soit livré aux mains des pécheurs, qu'il soit crucifié, et qu'il ressuscite le troisième jour.»\n\n### Response:\nA ye min fɔ ka a to Galile jamana na, aw ka aw hakili jigin o la, ko : \xa0A ka kan Mɔgɔ Denkɛ ka don hakɛkɛlaw bolo, ka gengen jiri kan ; o tile sabanan ka kunun ka bɔ suw cɛ la. »"}
{'text': '### Instruction:\nTraduis ce proverbe en bambara\n\n### Input:\nEt elles se rappelèrent ses paroles.\n\n### Response:\nO la, u hakili jiginna a ka kumaw la.'}
{'text': "### Instruction:\nRéponds en bambara\n\n### Input:\nLes Apôtres refusent d'ajouter foi aux dires des femmes\n\n### Response:\nKalandenw banni ka da musow ka fɔlenw la"}
{'text': '### Instruction:\nTraduire en bambara\n\n### Input:\nÀ leur retour du tombeau, elles rapportèrent tout cela aux Onze et à tous les autres.\n\n### Response:\nU nalen ka bɔ kaburu la, u ye nin kow bɛɛ lakali kalanden tan ni kelen ani tɔw ye.'}
{'text': "### Instruction:\nConvertis ce texte en bambara naturel\n\n### Input:\nC'étaient Marie la Magdaléenne, Jeanne et Marie, mère de Jacques. Les autres femmes qui étaient avec elles le dirent aussi aux apôtres;\n\n### Response:\nOlu ye Mari Madelɛni, Zaani ani Zaki ba Mari ye ani muso wɛrɛw."}
{'text': '### Instruction:\nTraduire en bambara\n\n### Input:\nmais ces propos leur semblèrent du radotage, et ils ne les crurent pas.\n\n### Response:\nNka kuma ninnu kɛra Cidenw tulo la kunfɛkumaw ye, u ma da a la.'}
{'text': '### Instruction:\nTraduire en bambara\n\n### Input:\nPierre au tombeau\n\n### Response:\nPiyɛri bɛ kaburu la'}
{'text': '### Instruction:\nTraduis ce poème en bambara\n\n### Input:\nPierre cependant partit et courut au tombeau. Mais, se penchant, il ne voit que les linges.\n\n### Response:\nO bɛɛ ni a ta, Piyɛri bolila ka taa kaburu la ; a ye a kun biri ka o kɔnɔna lajɛ minkɛ, a ɲɛ dara jalamuguw dɔrɔn de kan.'}
{'text': "### Instruction:\nTraduire en bambara\n\n### Input:\nEt il s'en alla chez lui, tout surpris de ce qui était arrivé.\n\n### Response:\nA ye a kɔsegin a ka so. Ko min kɛra, a kabakoyalenba tun bɛ o la."}
{'text': "### Instruction:\nTraduis cette phrase en bambara\n\n### Input:\nLes deux disciples d'Emmaüs\n\n### Response:\nEmayusi kalanden fila"}
{'text': '### Instruction:\nRéponds en bambara\n\n### Input:\net ils conversaient entre eux de tout ce qui était arrivé.\n\n### Response:\nKo minnu kɛra, u tun bɛ olu bɛɛ baro la.'}
{'text': "### Instruction:\nConvertis ce texte en bambara naturel\n\n### Input:\nEt il advint, comme ils conversaient et discutaient ensemble, que Jésus en personne s'approcha, et il faisait route avec eux;\n\n### Response:\nKa u to o kuma na, Yezu yɛrɛ ye a magɛrɛ u la ka taama u fɛ."}
{'text': '### Instruction:\nTraduis cette phrase en bambara\n\n### Input:\nmais leurs yeux étaient empêchés de le reconnaître.\n\n### Response:\nNka a tun kɛra iko ni dibi tun bɛ u ɲɛ na, ani u tun ma Yezu dɔn u dɔnbaga ye.'}
{'text': '### Instruction:\nConversation naturelle en bambara\n\n### Input:\nIl leur dit: «Quels sont donc ces propos que vous échangez en marchant?»\n\n### Response:\nYezu ko u ye: «Aw dun bɛ masala mun kan aw taamatɔ? »'}
{'text': "### Instruction:\nTraduis ce proverbe en bambara\n\n### Input:\nEt ils s'arrêtèrent, le visage sombre.\n\n### Response:\nU ye u jɔ ani u ɲɛnasisilen tun bɛ."}
{'text': "### Instruction:\nTraduis ce proverbe en bambara\n\n### Input:\nPrenant la parole, l'un d'eux, nommé Cléophas, lui dit: «Tu es bien le seul habitant de Jérusalem à ignorer ce qui y est arrivé ces jours-ci!»\n\n### Response:\nU dɔ la kelen, min tɔgɔ ko Kilewofasi, o ye a jaabi, ko: «Zerusalɛmukaw cɛ la e kelen de bɛ i kun fɛ, ka a masɔrɔ ko minnu kɛra tile damadɔ ninnu kɔnɔ, e tɛ olu dɔn! »"}
{'text': '### Instruction:\nDialogue entre amis en bambara\n\n### Input:\n«Quoi donc?» leur dit-il.\n\n### Response:\nA ko u ye: «Mun ko ye olu ye? »'}
{'text': "### Instruction:\nTraduis ce passage religieux en bambara\n\n### Input:\nIls lui dirent: «Ce qui concerne Jésus le Nazarénien, qui s'est montré un prophète puissant en oeuvres et en paroles devant Dieu et devant tout le peuple, comment nos grands prêtres et nos chefs l'ont livré pour être condamné à mort et l'ont crucifié.\n\n### Response:\nU ye a jaabi: «Min ye Nazarɛti Yezu sɔrɔ. Cɛ nin tun ye Kiraba ye. A se tun ka bon a ka walew ni a dalakumaw fɛ, Ala ni mɔgɔw ɲɛ kɔrɔ. \xa0Sɔnnikɛla kuntigiw ani ɲɛmɔgɔw ye a don bolo la ka a bila saya la, ka a gengen kuruwa kan."}
{'text': "### Instruction:\nNarration en bambara\n\n### Input:\nNous espérions, nous, que c'était lui qui allait délivrer Israël; mais avec tout cela, voilà le troisième jour depuis que ces choses sont arrivées!\n\n### Response:\nAnw kɔni jigi dalen tun bɛ a kan ko a na kɛ Isirayɛli kunmabɔbaga ye ! Nka o ko nin kɛra, o tile sabanan filɛ nin ye."}
{'text': '### Instruction:\nTraduire en bambara\n\n### Input:\nQuelques femmes qui sont des nôtres nous ont, il est vrai, stupéfiés.\n\n### Response:\nTiyɛn kɔni ka fɔ, an ka muso dɔw ye an hakili ɲagami, ka an kabakoya.'}
{'text': "### Instruction:\nConvertis ce texte en bambara naturel\n\n### Input:\nS'étant rendues de grand matin au tombeau et n'ayant pas trouvé son corps, elles sont revenues nous dire qu'elles ont même eu la vision d'anges qui le disent vivant.\n\n### Response:\nU taara kaburu la sɔgɔmada joona fɛ, \xa0ani u ma a su ye. U nana a lakali an ye fana ko u ɲɛ dara mɛlɛkɛ dɔw kan minnu ye a fɔ u ye ko a bɛ balo la."}
{'text': "### Instruction:\nTraduire en bambara\n\n### Input:\nQuelques-uns des nôtres sont allés au tombeau et ont trouvé les choses tout comme les femmes avaient dit; mais lui, ils ne l'ont pas vu!»\n\n### Response:\nAn jɛɲɔgɔn dɔw taara kaburu la ani iko musow tun ye a fɔ cogo min, u ye koɲɛ sɔrɔ o cogo la nka u ma ale yɛrɛ ye. »"}
{'text': "### Instruction:\nTraduis ce passage religieux en bambara\n\n### Input:\nAlors il leur dit: «O coeurs sans intelligence, lents à croire à tout ce qu'ont annoncé les Prophètes!\n\n### Response:\nO la, Yezu ko u ye : « Kodɔnbali ninnu, aw ma faamuyali kɛ ni ka da kiraw ka kumaw bɛɛ la !"}
{'text': '### Instruction:\nDiscussion en bambara\n\n### Input:\nNe fallait-il pas que le Christ endurât ces souffrances pour entrer dans sa gloire?»\n\n### Response:\nWaajibi tun tɛ wa ko Krista ka tɔɔrɔ ninnu bɛɛ muɲu walasa ka don a ka nɔɔrɔ la ? »'}
{'text': '### Instruction:\nTexte religieux en bambara\n\n### Input:\nEt, commençant par Moïse et parcourant tous les Prophètes, il leur interpréta dans toutes les Écritures ce qui le concernait.\n\n### Response:\nO tuma na sa, ko minnu bɛɛ tun bɛ Cidenmasa kun kan ni o sɛbɛnnen bɛ Kitabu Senu kɔnɔ, ka a daminɛ Moyizi ni kiraw bɛɛ ma, a ye olu kɔrɔ jira u la.'}
{'text': "### Instruction:\nRaconte cette histoire en bambara\n\n### Input:\nQuand ils furent près du village où ils se rendaient, il fit semblant d'aller plus loin.\n\n### Response:\nU surunyana u taayɔrɔ la minkɛ, Yezu ye a kɛ iko a bɛ taa ɲɛ."}
{'text': '### Instruction:\nRéponds en bambara\n\n### Input:\nMais ils le pressèrent en disant: «Reste avec nous, car le soir tombe et le jour déjà touche à son terme.»\n\n### Response:\nNka u ye u labalan a ma, ko : « To an fɛ, katugu wula sera ani tile bɛ ɲini ka bin. »'}
{'text': '### Instruction:\nConvertis ce texte en bambara naturel\n\n### Input:\nIl entra donc pour rester avec eux.\n\n### Response:\nO la, a donna ka to u fɛ.'}
{'text': "### Instruction:\nConte traditionnel en bambara\n\n### Input:\nEt il advint, comme il était à table avec eux, qu'il prit le pain, dit la bénédiction, puis le rompit et le leur donna.\n\n### Response:\nKa u sigilen to dumuni kun na, a ye buuru ta ka dubaw kɛ ; a ye buuru tila-tila ka o di u ma."}
{'text': "### Instruction:\nTraduire en bambara\n\n### Input:\nLeurs yeux s'ouvrirent et ils le reconnurent...\n\n### Response:\nU ɲɛ yɛlɛla ani u ye a dɔn."}
{'text': '### Instruction:\nTraduis cette phrase en bambara\n\n### Input:\nmais il avait disparu de devant eux.\n\n### Response:\nNka a tununna u ɲɛ kɔrɔ.'}
{'text': "### Instruction:\nRéponse conversationnelle en bambara\n\n### Input:\nEt ils se dirent l'un à l'autre: «Notre coeur n'était-il pas tout brûlant au-dedans de nous, quand il nous parlait en chemin, quand il nous expliquait les Écritures?»\n\n### Response:\nO la, u ko ɲɔgɔn ye : « Ka a to kuma na an ye sira fɛ ka Kitabu Senu kɔrɔ fɔ an ye, an dusukun tun tɛ goniya la an kɔnɔ wa ?»"}
{'text': "### Instruction:\nTraduire en bambara\n\n### Input:\nÀ cette heure même, ils partirent et s'en retournèrent à Jérusalem.\n\n### Response:\nO yɔrɔnin bɛɛ, u wulila ka u kɔsegin Zerusalɛmu."}

In [ ]:
import json
import random
import os

# =========================================================
# CHEMIN DATASET
# =========================================================

dataset_path = "/content/drive/MyDrive/bambara/dataset.jsonl"

# =========================================================
# DONNÉES DE BASE
# =========================================================

translation_data = [
    ("Bonjour", "I ni sogoma"),
    ("Comment vas-tu ?", "I ka kɛnɛ wa ?"),
    ("Je vais bien merci", "N ka kɛnɛ, i ni ce"),
    ("Où vas-tu ?", "I bɛ taa min ?"),
    ("Je suis fatigué", "N sɛkɛna"),
    ("Le professeur est arrivé", "Karamɔgɔ nana"),
    ("Je vais à l'école", "N bɛ taa kalanso la"),
    ("J'ai faim", "N kɔkɔ bɛ n la "),
    ("J'ai mal à la tête", "Kun bɛ n dimi"),
    ("Je veux manger", "N b'a fɛ ka dumuni kɛ"),
]

conversation_data = [
    # AMIS
    ("Conversation entre amis", "Salut mon frère", "Teri, i ka kɛnɛ wa ?"),
    ("Conversation entre amis", "On se voit demain ?", "an bɛ ɲɔgɔn ye sini?"),
    ("Conversation entre amis", "Je rentre à la maison", "N bɛ taa so"),

    # ÉCOLE
    ("Conversation à l'école", "Le professeur arrive", "Karamɔgɔ bɛ na"),
    ("Conversation à l'école", "Ouvre ton cahier", "I ka cahier dayɛlɛ"),
    ("Conversation à l'école", "Je n'ai pas compris", "N ma faamu"),

    # HÔPITAL
    ("Conversation à l'hôpital", "Je suis malade", "Banna bɛ n na"),
    ("Conversation à l'hôpital", "Appelez le médecin", "Dɔgɔtɔrɔ wele"),
    ("Conversation à l'hôpital", "J'ai besoin d'aide", "N manko bɛ dɛmɛ la"),

    # MARCHÉ
    ("Conversation au marché", "Combien ça coûte ?", "O ye joli ye?"),
    ("Conversation au marché", "C'est trop cher", "A ka kɛlɛ kosɛbɛ"),
]

# =========================================================
# VARIATION D'INSTRUCTION (IMPORTANT POUR ÉVITER OVERFIT)
# =========================================================

translation_instructions = [
    "Traduire en bambara",
    "Traduis cette phrase en bambara",
    "Convertis en bambara",
]

# =========================================================
# ÉCRITURE JSONL
# =========================================================

def write_sample(text):
    with open(dataset_path, "a", encoding="utf-8") as f:
        json.dump({"text": text}, f, ensure_ascii=False)
        f.write("\n")

# =========================================================
# AJOUT TRADUCTION (70%)
# =========================================================

print("Ajout des données de traduction...")

random.shuffle(translation_data)

for fr, bm in translation_data:
    instruction = random.choice(translation_instructions)

    text = f"""### Instruction:
{instruction}

### Input:
{fr}

### Response:
{bm}"""

    write_sample(text)

# =========================================================
# AJOUT CONVERSATION (30%)
# =========================================================

print("Ajout des conversations...")

random.shuffle(conversation_data)

for instr, inp, out in conversation_data:

    # légère variation pour rendre le dataset plus naturel
    variation = random.choice([
        instr,
        instr + " (dialogue)",
        instr + " entre deux personnes"
    ])

    text = f"""### Instruction:
{variation}

### Input:
{inp}

### Response:
{out}"""

    write_sample(text)

print("Ajout terminé avec succès ✔")

Ajout des données de traduction...
Ajout des conversations...
Ajout terminé avec succès ✔

In [ ]:
import torch

print("GPU disponible :", torch.cuda.is_available())

if torch.cuda.is_available():
    print("Nom du GPU :", torch.cuda.get_device_name(0))
    print("Nombre de GPU :", torch.cuda.device_count())

    # mémoire GPU
    print("Mémoire totale :", round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2), "GB")

else:
    print("Aucun GPU détecté")

GPU disponible : True
Nom du GPU : Tesla T4
Nombre de GPU : 1
Mémoire totale : 14.56 GB